[package]
name = "chombot"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description = "Discord bot for Riichi Mahjong servers."
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chombot-common.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
poise.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
