[package]
name = "chombot-kcc"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description = "Discord bot for Riichi Mahjong servers - Krakow Chombo Club modified version."
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
chombot-common.workspace = true
chrono-tz.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
poise.workspace = true
reqwest.workspace = true
riichi_hand.workspace = true
serde.workspace = true
slug.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
